# Generated by Django 6.0.5 on 2026-05-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Доступное количество копий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='authors.author', verbose_name='Автор')),
            ],
        ),
    ]
